import type { ApiDefinition } from "./api-schema";

export const apiCatalog: ApiDefinition[] = [
  {
    id: "60s-news",
    name: "60s Daily News",
    provider: "60s API",
    category: "News",
    description: "A compact daily brief sourced from the 60s open API collection.",
    method: "GET",
    baseUrl: "https://60s.viki.moe",
    path: "/v2/60s",
    auth: "none",
    authLabel: "Public endpoint",
    params: [{ name: "encoding", label: "Encoding", type: "string", required: false, defaultValue: "json", description: "Use json, text, or image." }],
    tags: ["60s", "brief", "headlines"],
    sourceUrl: "https://github.com/vikiboss/60s",
    sampleResponse: { date: "2026-08-05", news: [{ title: "Open data teams ship smaller, clearer products", url: "https://example.com/news/1" }, { title: "Global markets open with mixed signals", url: "https://example.com/news/2" }], tip: "Build a useful thing with the data you can explain." },
  },
  {
    id: "60s-weather",
    name: "Weather Realtime",
    provider: "60s API",
    category: "Weather",
    description: "Realtime weather lookup with a small, dashboard-friendly response.",
    method: "GET",
    baseUrl: "https://60s.viki.moe",
    path: "/v2/weather/realtime",
    auth: "none",
    authLabel: "Public endpoint",
    params: [{ name: "city", label: "City", type: "string", required: false, defaultValue: "Shanghai", description: "City name in Chinese or English." }],
    tags: ["weather", "realtime", "60s"],
    sourceUrl: "https://docs.60s-api.viki.moe",
    sampleResponse: { city: "Shanghai", weather: "Cloudy", temperature: 28, feelsLike: 30, humidity: 67, wind: "SE 3 m/s", updatedAt: "2026-08-05T08:30:00Z" },
  },
  {
    id: "60s-exchange",
    name: "Exchange Rates",
    provider: "60s API",
    category: "Finance",
    description: "A ready-to-wire exchange rate endpoint for finance cards and alerts.",
    method: "GET",
    baseUrl: "https://60s.viki.moe",
    path: "/v2/exchange-rate",
    auth: "none",
    authLabel: "Public endpoint",
    params: [{ name: "currency", label: "Base currency", type: "string", required: false, defaultValue: "USD", description: "ISO 4217 code." }],
    tags: ["fx", "currency", "60s"],
    sourceUrl: "https://github.com/vikiboss/60s",
    sampleResponse: { base: "USD", rates: { CNY: 7.18, EUR: 0.92, JPY: 147.2 }, updatedAt: "2026-08-05T08:00:00Z" },
  },
  {
    id: "cat-fact",
    name: "Cat Fact",
    provider: "The Cat API",
    category: "Lifestyle",
    description: "A lightweight public endpoint for testing text cards and list widgets.",
    method: "GET",
    baseUrl: "https://catfact.ninja",
    path: "/fact",
    auth: "none",
    authLabel: "Public endpoint",
    params: [],
    tags: ["demo", "text", "public"],
    sourceUrl: "https://catfact.ninja/",
    sampleResponse: { fact: "Cats spend a large part of their day grooming.", length: 52 },
  },
  {
    id: "github-repository",
    name: "GitHub Repository",
    provider: "GitHub REST API",
    category: "Developer",
    description: "Inspect public repository metadata and use it as a metric or table source.",
    method: "GET",
    baseUrl: "https://api.github.com",
    path: "/repos/{owner}/{repo}",
    auth: "none",
    authLabel: "Public repositories",
    params: [
      { name: "owner", label: "Owner", type: "string", required: true, defaultValue: "Superkimi", description: "GitHub owner or organization." },
      { name: "repo", label: "Repository", type: "string", required: true, defaultValue: "Vibe-API", description: "Repository name." },
    ],
    tags: ["github", "repo", "developer"],
    sourceUrl: "https://docs.github.com/en/rest/repos/repos#get-a-repository",
    sampleResponse: { full_name: "Superkimi/Vibe-API", description: "Compose APIs with a visual canvas and AI.", stargazers_count: 128, open_issues_count: 7, language: "TypeScript", updated_at: "2026-08-05T07:40:00Z" },
  },
  {
    id: "open-exchange",
    name: "Open Exchange",
    provider: "Open ER API",
    category: "Finance",
    description: "A public exchange-rate response with a broad currency map.",
    method: "GET",
    baseUrl: "https://open.er-api.com",
    path: "/v6/latest/USD",
    auth: "none",
    authLabel: "Public endpoint",
    params: [],
    tags: ["fx", "rates", "public"],
    sourceUrl: "https://www.exchangerate-api.com/docs/free",
    sampleResponse: { result: "success", base_code: "USD", rates: { CNY: 7.18, EUR: 0.92, GBP: 0.78, JPY: 147.2 }, time_last_update_utc: "Wed, 05 Aug 2026 00:00:01 +0000" },
  },
  {
    id: "json-placeholder",
    name: "Todo Item",
    provider: "JSONPlaceholder",
    category: "Utilities",
    description: "Stable sample JSON for prototyping mapping, detail panels, and table output.",
    method: "GET",
    baseUrl: "https://jsonplaceholder.typicode.com",
    path: "/todos/{id}",
    auth: "none",
    authLabel: "Public endpoint",
    params: [{ name: "id", label: "Todo id", type: "number", required: true, defaultValue: 1, description: "Any id from 1 to 200." }],
    tags: ["mock", "json", "prototype"],
    sourceUrl: "https://jsonplaceholder.typicode.com/",
    sampleResponse: { userId: 1, id: 1, title: "Connect a real API to your first card", completed: false },
  },
  {
    id: "random-user",
    name: "Random User",
    provider: "Random User Generator",
    category: "Lifestyle",
    description: "Generate a profile-shaped object for tables, avatars, and contact cards.",
    method: "GET",
    baseUrl: "https://randomuser.me",
    path: "/api",
    auth: "none",
    authLabel: "Public endpoint",
    params: [],
    tags: ["profile", "list", "demo"],
    sourceUrl: "https://randomuser.me/documentation",
    sampleResponse: { results: [{ name: { first: "Mina", last: "Zhao" }, email: "mina.zhao@example.com", location: { city: "Shanghai" } }], info: { results: 1 } },
  },
  {
    id: "nasa-apod",
    name: "NASA Astronomy Picture",
    provider: "NASA Open APIs",
    category: "Lifestyle",
    description: "A visual daily content source for editorial dashboards and discovery pages.",
    method: "GET",
    baseUrl: "https://api.nasa.gov",
    path: "/planetary/apod",
    auth: "queryKey",
    authLabel: "DEMO_KEY or your NASA key",
    params: [{ name: "api_key", label: "NASA API key", type: "string", required: true, defaultValue: "DEMO_KEY", description: "Use a project key for production." }],
    tags: ["image", "nasa", "editorial"],
    sourceUrl: "https://api.nasa.gov/",
    sampleResponse: { title: "The Milky Way over the Southern Ocean", explanation: "A sample astronomy editorial card.", media_type: "image", url: "https://apod.nasa.gov/apod/image/2608/sample.jpg", date: "2026-08-05" },
  },
];

export function getApiDefinition(apiId: string) {
  return apiCatalog.find((api) => api.id === apiId);
}
